#!/usr/bin/env python3
"""Wrap the handbook fragment into a standalone, servable HTML document.

``docs/skill-handbook.body.html`` is the source. It is a *fragment* — no
doctype, no ``<html>``, no ``<head>`` — because that is what the Artifact
publisher expects; it supplies the skeleton itself.

Served from a static host, that same fragment renders in quirks mode, with no
declared charset (the arrows and em-dashes are the first casualties) and no
viewport, so a phone gets a desktop-width page zoomed out. This adds exactly
the skeleton the publisher would have, and nothing else.

One source, two outputs — so there is no second copy of the prose to drift.

    python scripts/build-handbook.py            # regenerate
    python scripts/build-handbook.py --check    # exit 1 if stale
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BODY = ROOT / "docs" / "skill-handbook.body.html"
PAGE = ROOT / "docs" / "skill-handbook.html"

BANNER = "<!-- generated by scripts/build-handbook.py from skill-handbook.body.html -->"

SKELETON = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="color-scheme" content="light dark">
<meta name="description" content="{description}">
{banner}
{head}
</head>
<body>
{body}
</body>
</html>
"""

DESCRIPTION = (
    "How the Palette agent skill is built, released, kept current, "
    "consumed in CUGA and Claude Code, and verified."
)


def render() -> str:
    fragment = BODY.read_text(encoding="utf-8")
    # <title> and <style> belong in the head; everything else is the body.
    head_parts = re.findall(r"<title>.*?</title>|<style>.*?</style>", fragment, re.DOTALL)
    body = fragment
    for part in head_parts:
        body = body.replace(part, "", 1)
    return SKELETON.format(
        description=DESCRIPTION,
        banner=BANNER,
        head="\n".join(p.strip() for p in head_parts),
        body=body.strip(),
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit 1 if the page is stale")
    args = parser.parse_args(argv)

    rendered = render()
    if args.check:
        current = PAGE.read_text(encoding="utf-8") if PAGE.is_file() else ""
        if current != rendered:
            print(
                f"{PAGE.relative_to(ROOT)} is stale — run `make handbook` and commit the result.",
                file=sys.stderr,
            )
            return 1
        print("handbook is up to date with its source")
        return 0

    PAGE.write_text(rendered, encoding="utf-8")
    print(f"wrote {PAGE.relative_to(ROOT)}  ({PAGE.stat().st_size / 1024:.0f} KB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
